name: Build and Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.APIKEY }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Replace API key placeholder
        run: |
          sed -i "s/__API_KEY__/${APIKEY}/g" script.js

      - name: Mask APIKEY (safeguard)
        run: echo "::add-mask::${{ secrets.APIKEY }}"

      - name: Serve the website
        run: |
          echo "Serving the website..."
          cat script.js
