name: Inject Line into JS and Commit

on: [push]

jobs:
  inject-line:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Inject Console Log into script.js
        run: echo "console.log('Injected Config!');" >> script.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add script.js
          git commit -m "Injected console.log into script.js"
          git push
