name: Deploy with Secret
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Dynamic File
        env:
          SECRET_WORD: ${{ secrets.HIDDEN_WORD }}
        run: |
          echo "document.getElementById('output').innerHTML = '${SECRET_WORD}';" > script.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.PAGES_TOKEN }}
          BRANCH: gh-pages

      - name: Clean Up
        run: rm script.js
