name: Build and Run Website

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.APIKEY }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Mask APIKEY (safeguard)
        run: echo "::add-mask::${{ secrets.APIKEY }}"

      - name: Run Application
        run: npm start
