name: Deploy with Secret
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace Secret Placeholder
        env:
          SECRET_WORD: ${{ secrets.HIDDEN_WORD }}
        run: |
          sed -i "s/__SECRET_WORD__/${SECRET_WORD}/g" script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # The directory containing the files to be deployed

      - name: Clean Up
        run: |
          # Optionally clean up any generated files if needed
          echo "Clean up step"
