name: Inject Secrets into JS

on: [push]

jobs:
  inject-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Inject Secrets into script.js
        run: |
          echo "console.log('Injected Config!');" >> script.js
