name: Deploy with Secret
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Dynamic File
        env:
          SECRET_WORD: ${{ secrets.HIDDEN_WORD }}
        run: |
          echo "document.getElementById('output').innerHTML = '${SECRET_WORD}';" > script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # The directory containing the files to be deployed

      - name: Clean Up
        run: rm script.js  # Delete the generated file to avoid committing it
