name: Set Environment Variables

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create env.js file
        run: |
          echo "const config = {" > env.js
          echo "  APIKEY: '${{ secrets.APIKEY }}'," >> env.js
          echo "  APPID: '${{ secrets.APPID }}'," >> env.js
          echo "  AUTHDOMAIN: '${{ secrets.AUTHDOMAIN }}'," >> env.js
          echo "  DATABASEURL: '${{ secrets.DATABASEURL }}'," >> env.js
          echo "  MESSAGINGSENDERID: '${{ secrets.MESSAGINGSENDERID }}'," >> env.js
          echo "  PROJECTID: '${{ secrets.PROJECTID }}'," >> env.js
          echo "  STORAGEBUCKET: '${{ secrets.STORAGEBUCKET }}'" >> env.js
          echo "};" >> env.js
          echo "export default config;" >> env.js

      - name: Append env.js to script.js
        run: |
          echo "import config from './env.js';" >> script.js
          echo "const apikey = config.APIKEY;" >> script.js
          echo "const appid = config.APPID;" >> script.js
          echo "const authdomain = config.AUTHDOMAIN;" >> script.js
          echo "const databaseurl = config.DATABASEURL;" >> script.js
          echo "const messagingsenderid = config.MESSAGINGSENDERID;" >> script.js
          echo "const projectid = config.PROJECTID;" >> script.js
          echo "const storagebucket = config.STORAGEBUCKET;" >> script.js
