name: Inject Secrets

on: [push]

jobs:
  inject-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create script.js with Secrets
        run: |
          echo "const config = {" > script.js
          echo "  APIKEY: '${{ secrets.APIKEY }}'," >> script.js
          echo "  APPID: '${{ secrets.APPID }}'," >> script.js
          echo "  AUTHDOMAIN: '${{ secrets.AUTHDOMAIN }}'," >> script.js
          echo "  DATABASEURL: '${{ secrets.DATABASEURL }}'," >> script.js
          echo "  MESSAGINGSENDERID: '${{ secrets.MESSAGINGSENDERID }}'," >> script.js
          echo "  PROJECTID: '${{ secrets.PROJECTID }}'," >> script.js
          echo "  STORAGEBUCKET: '${{ secrets.STORAGEBUCKET }}'" >> script.js
          echo "};" >> script.js
          echo "console.log(config);" >> script.js

      - name: Verify script.js
        run: cat script.js
